// Generates supabase/seed/products.sql from supabase/seed/products.json.
// Run: node seed/build-seed.mjs
// Adding products later is a JSON edit + re-run, not an engineering task.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const seedDir = path.join(dir, "..", "supabase", "seed");
const data = JSON.parse(fs.readFileSync(path.join(seedDir, "products.json"), "utf8"));

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => (v == null || v === "" ? "NULL" : Number(v));
const arr = (a) =>
  !a || !a.length ? "'{}'" : `ARRAY[${a.map(q).join(", ")}]::text[]`;

const cols = [
  "name", "brand", "collection", "designer", "category",
  "width_mm", "depth_mm", "height_mm", "seat_height_mm", "diameter_mm",
  "materials", "finish", "colour",
  "price_amount", "price_currency", "price_type", "lead_time_weeks",
  "description_en", "description_it", "source_type",
];

const rows = data.products.map((p) =>
  `  (${[
    q(p.name), q(p.brand), q(p.collection), q(p.designer), q(p.category),
    num(p.width_mm), num(p.depth_mm), num(p.height_mm), num(p.seat_height_mm), num(p.diameter_mm),
    arr(p.materials), q(p.finish), q(p.colour),
    num(p.price_amount), q(p.price_currency || "EUR"), q(p.price_type || "trade"), num(p.lead_time_weeks),
    q(p.description_en), q(p.description_it), "'seed'",
  ].join(", ")})`,
);

const sql = `-- Generated by seed/build-seed.mjs from products.json. Do not edit by hand.
-- Global library rows (studio_id = NULL). Re-runnable: clears prior seed first.

delete from products where source_type = 'seed' and studio_id is null;

insert into products (${cols.join(", ")}) values
${rows.join(",\n")};
`;

fs.writeFileSync(path.join(seedDir, "products.sql"), sql);
console.log(`Wrote supabase/seed/products.sql with ${data.products.length} products.`);
